---
title: "Allegheny Jail Census"
author: "by Andrew Olson"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: cosmo
---

```{r setup, include=FALSE}
#loading libraries used
library(flexdashboard)
library(shiny)
library(reshape2)
library(dplyr)
library(plotly)
library(htmltools)
library(httr)

#Building the WPRDC Get request
ckanSQL <- function(url) {
  # Make the Request
  r <- RETRY("GET", URLencode(url))
  # Extract Content
  c <- content(r, "text")
  # Basic gsub to make NA's consistent with R
  json <- gsub('NaN', 'NA', c, perl = TRUE)
  # Create Dataframe
  data.frame(jsonlite::fromJSON(json)$result$records)
}

races <- sort(c("Black", "White", "Hispanic", "Asian", "American Indian"))

jaInput <- reactive({
  #building API query with date filter
  url <-paste0("http://data.wprdc.org/api/3/action/datastore_search_sql?sql=SELECT%20%22Date%22%2C%20%22Gender%22%2C%20%22Race%22%2C%20%22Age%20at%20Booking%22%20AS%20%22AgeatBooking%22%20FROM%20%2266cdcd57-6c92-4aaa-8800-0ed9d8f03e22%22%20WHERE%20%22Date%22%20%3E=%20%27", input$DateSelect[1], "%27%20AND%20%22Date%22%20%3C=%20%27", input$DateSelect[2], "%27")
  
  #load and clean data
  jail.load <- ckanSQL(url) %>%
    mutate(Gender = recode(Gender, "M" = "Male", "F" = "Female"),
           Race = factor(recode(Race, "B" = "Black",
                                  "W" = "White",
                                  "H" = "Hispanic",
                                  "A" = "Asian",
                                  "I" = "American Indian",
                                  "U" = "Unknown",
                                  "x" = NULL), levels = c("Black", "White", "Hispanic", "Asian", "American Indian", "Unknown")),
           Date = as.Date(Date),
           AgeatBooking = as.numeric(AgeatBooking))

  # Booking Age Filter
  jail <- jail.load %>% 
    filter(AgeatBooking >= input$BookingAgeSelect[1] & AgeatBooking <= input$BookingAgeSelect[2])
  # Race Filter
  if (length(input$RaceSelect) > 0 ) {
    jail <- subset(jail, Race %in% input$RaceSelect)
  }
  if (length(input$GenderSelect) > 0 ) {
    jail <- subset(jail, Gender %in% input$GenderSelect)
  }
  
  return(jail)
})

#Reactive function for gender guage
jaGInput <- reactive({
  #building API query with date filter
  url <-paste0("http://data.wprdc.org/api/3/action/datastore_search_sql?sql=SELECT%20%22Date%22%2C%20%22Gender%22%2C%20%22Race%22%2C%20%22Age%20at%20Booking%22%20AS%20%22AgeatBooking%22%20FROM%20%2266cdcd57-6c92-4aaa-8800-0ed9d8f03e22%22%20WHERE%20%22Date%22%20%3E=%20%27", input$DateSelect[1], "%27%20AND%20%22Date%22%20%3C=%20%27", input$DateSelect[2], "%27")
  
  #load and clean data
  jail.load <- ckanSQL(url) %>%
    mutate(Race = factor(recode(Race, "B" = "Black",
                                  "W" = "White",
                                  "H" = "Hispanic",
                                  "A" = "Asian",
                                  "I" = "American Indian",
                                  "U" = "Unknown",
                                  "x" = NULL), levels = c("Black", "White", "Hispanic", "Asian", "American Indian", "Unknown")),
           Gender = recode(Gender, "M" = "Male", "F" = "Female"),
           Date = as.Date(Date),
           AgeatBooking = as.numeric(AgeatBooking))

  # Booking Age Filter
  jail <- jail.load %>% 
    filter(AgeatBooking >= input$BookingAgeSelect[1] & AgeatBooking <= input$BookingAgeSelect[2])
  # Race Filter
  if (length(input$RaceSelect) > 0 ) {
    jail <- subset(jail, Race %in% input$RaceSelect)
  }
  
  return(jail)
})

#Reactive function for race valuebox
jaRInput <- reactive({
  #building API query with date filter
  url <-paste0("http://data.wprdc.org/api/3/action/datastore_search_sql?sql=SELECT%20%22Date%22%2C%20%22Gender%22%2C%20%22Race%22%2C%20%22Age%20at%20Booking%22%20AS%20%22AgeatBooking%22%20FROM%20%2266cdcd57-6c92-4aaa-8800-0ed9d8f03e22%22%20WHERE%20%22Date%22%20%3E=%20%27", input$DateSelect[1], "%27%20AND%20%22Date%22%20%3C=%20%27", input$DateSelect[2], "%27")
  
  #load and clean data
  jail.load <- ckanSQL(url) %>%
    mutate(Race = factor(recode(Race, "B" = "Black",
                                  "W" = "White",
                                  "H" = "Hispanic",
                                  "A" = "Asian",
                                  "I" = "American Indian",
                                  "U" = "Unknown",
                                  "x" = NULL), levels = c("Black", "White", "Hispanic", "Asian", "American Indian", "Unknown")),
           Gender = recode(Gender, "M" = "Male", "F" = "Female"),
           Date = as.Date(Date),
           AgeatBooking = as.numeric(AgeatBooking))

  # Booking Age Filter
  jail <- jail.load %>% 
    filter(AgeatBooking >= input$BookingAgeSelect[1] & AgeatBooking <= input$BookingAgeSelect[2])
  # Race Filter
  if (length(input$RaceSelect) > 0 ) {
    jail <- subset(jail, Race %in% input$RaceSelect)
  }
  if (length(input$GenderSelect) > 0 ) {
    jail <- subset(jail, Gender %in% input$GenderSelect)
  }
  
  return(jail)
})

#Reset filters
observeEvent(input$reset, {
    updateSelectInput(session, "RaceSelect", selected = c("Black", "White"))
    updateSliderInput(session, "BookingAgeSelect", value = c(18, 40))
    updateDateRangeInput(session, "DateSelect", start = Sys.Date()-30, end = Sys.Date())
    updateCheckboxGroupInput(session, "GenderSelect", choices = c("Male", "Female"), selected = c("Male", "Female"))
    showNotification("You have successfully reset the filters", type = "message")
  })
```

Sidebar {.sidebar}
=====================================

```{r}
#Race Selecter
selectInput("RaceSelect",
               "Race:",
               choices = races,
               multiple = TRUE,
               selectize = TRUE,
               selected = c("Black", "White"))
#Booking Age Selecter
sliderInput("BookingAgeSelect",
               "Age at Booking:",
               min = 14,
               max = 90,
               value = c(18, 40),
               step = 1)
#Gender Selecter
checkboxGroupInput("GenderSelect",
                   "Gender:",
                   choices = c("Male", "Female"),
                   selected = c("Male", "Female"))
#Date Selecter
dateRangeInput("DateSelect",
               "Date range:",
               start = Sys.Date()-30,
               end = Sys.Date(),
               format = "mm/dd/yyyy")
#Reset Button
actionButton("reset", "Reset Filters", icon = icon("refresh"))
```

General
=====================================

Row 
-------------------------------------

### 

```{r}
#Average Age at booking value box
renderValueBox({
  ja <- jaInput()
  num <- round(mean(ja$AgeatBooking, na.rm = T), 0)
  valueBox("Avg Age at Booking", value = num, color = "purple")
})
```


### % Men in Jail

```{r}
#Guage of gender breakdown
renderGauge({
  ja <- jaGInput()
  rate <- round((sum(ja$Gender == "Male")) / length(ja$Gender) * 100, 1)
  gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(70, 100), warning = c(40, 69), danger = c(0, 30), colors = c("aqua", "green", "fuchsia")))
})
```

### 

```{r}
renderValueBox({
  ja <- jaRInput()
  num <- round((sum(ja$Race == "White", na.rm = TRUE) / sum(ja$Race == "Black", na.rm = TRUE)), 2)
  valueBox("Ratio of White to Black Prisoners", value = num, color = "green")
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### Daily Jail Census

```{r}
#Daily count
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = Date)) + 
      geom_bar(fill = "steelblue")+
      labs(x = "Date", title = "Jail Census by Day") +
      guides(color = FALSE)
})

```

### Age at Booking

```{r}
#plot of age at booking
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = AgeatBooking)) + 
        geom_histogram(fill = "forestgreen")+
        labs(x = "Age at Booking", title = "Age at Booking") +
        guides(color = FALSE)
  })
```

Race
=====================================

Row 
-------------------------------------

### 

```{r}
renderValueBox({
  # See above
  ja <- jaRInput()
  num <- round((sum(ja$Race == "White", na.rm = TRUE) / sum(ja$Race == "Black", na.rm = TRUE)), 2)
  valueBox("Ratio of White to Black Prisoners", value = num, color = "green")
})
```

Row 
-------------------------------------

### Daily Jail Census

```{r}
#Daily count
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = Date, fill = Race)) +
      geom_bar(position = "dodge")+
      scale_fill_manual(values = c("darkslategray", "dodgerblue3", "gold3", "red", "chartreuse", "blueviolet", "gray")) +
      labs(x = "Date", title = "Jail Census by Day") +
      guides(color = FALSE)
})
```

Row 
-------------------------------------

### Age at Booking

```{r}
#plot of age at booking
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = AgeatBooking)) +
      geom_area(stat = "bin", data = dat, aes(fill = Race), position = "stack")+
      scale_fill_manual(values = c("darkslategray", "dodgerblue3", "gold3", "red", "chartreuse", "blueviolet", "gray")) +
      labs(x = "Age at Booking", color = "Race", title = "Age at Booking") +
      guides(color = FALSE)
  })
```

Gender
=====================================

Row 
-------------------------------------

### % Men in Jail

```{r}
#Guage of gender breakdown
renderGauge({
  ja <- jaGInput()
  rate <- round((sum(ja$Gender == "Male")) / length(ja$Gender) * 100, 1)
  gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(70, 100), warning = c(40, 69), danger = c(0, 30), colors = c("aqua", "green", "fuchsia")))
})
```

Row
-------------------------------------

### Daily Jail Census

```{r}
#Daily count
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = Date, fill = Gender)) + 
      geom_bar(position = position_stack(reverse = T))+
      labs(x = "Date", title = "Jail Census by Day") +
      guides(color = FALSE)
})

```

Row 
-------------------------------------

### Age at Booking

```{r}
#plot 2
renderPlotly({
    dat <- jaInput()
    ggplot(data = dat, aes(x = AgeatBooking)) + 
        geom_area(stat = "bin", data = dat, aes(fill = Gender), position = position_stack(reverse = T))+
        labs(x = "Age at Booking", title = "Age at Booking per Gender") +
        guides(color = FALSE)
})
```

Table
=====================================

Row 
-------------------------------------

### Table 

```{r}
DT::renderDataTable({
  subset(jaInput(), select = c(Date, Gender, Race, AgeatBooking))
})
```
